### PR TITLE
refactor(theme/book): Split into modules

### LINKED ISSUE #559: Error in console
`themePopup is undefined` - happens when you scroll immediately after loading the page. Introduced by #551, since `themePopup` is defined after `DOMContentLoaded` is fired, but `hideTheme` is called on scroll, which may happen before the event is fired.

Does not affect the functionality of the page.

### PR DESCRIPTION
**Pull request by sorin-davidoi**
Advantages:
 - Easier to reason about
 - Can easily disable some modules when debugging
 - Shared dependencies are explicit (playpen_text)
 - Enables some fancier things later one (e.g. run `codeSnippets` slightly later, to avoid blocking the page)

I'm aware that `codeSnippets` should be split into the highlighter and the editor, but I'm not sure I understand exactly how they interact so I've left it as it is for now.

~Also replaced some occurences of `let` with `var` (for consistency).~

Closes #559.

### CODE REVIEW

**Comment by projektir** [comment]
This looks great! Ran this on RBE, not seeing issues so far...

> Also replaced some occurences of `let` with `var` (for consistency).

This is a bit confusing (maybe even alarming) to me. `let` and `var` do different things, there's no need to make them consistent, and, if anything, `let` should be preferred... changing this could, in theory, change functionality, by making something previously only available to a block available in broader scope.

Probably not the case for this particular code file but I disagree with the reasoning, if anything, we should be moving towards using `let` more.

**Comment by sorin-davidoi** [comment]
There was no need for them to be let in the first place, since they are constants. Should we make the switch they other way around - only use const and let?

**Comment by projektir** [comment]
Yes, we can fix all that up in a different PR. LGTM, would probably be best if another person also pulls this down and checks for issues, though.

**Comment by Havvy** [comment]
All of the empty lines have an extra space on them.

**Comment by Michael-F-Bryan** [comment]
@sorin-davidoi, #557 is fixed now so if you rebase onto `master` all the CI checks should pass.

This looks like it's ready to merge, although you'll probably want to clean up the whitespace issue @Havvy mentioned first.

**Pull request merged**
