### PR TITLE
Fix URL in Cargo.toml

### PR DESCRIPTION
**Pull request by steveklabnik**

### CODE REVIEW

**Comment by steveklabnik** [comment]
Oh yeah, I mostly wanted to see that Travis is still running :)

**Comment by Michael-F-Bryan** [comment]
I'm pretty sure travis should still run because the git user details and `GH_TOKEN` being used in `ci/deploy.sh` stayed the same. I'll create another issue to deal with updating links and stuff.

**Comment by Michael-F-Bryan** [comment]
@steveklabnik, it looks like travis and GitHub Pages are working so do we still need this PR?

**Comment by steveklabnik** [comment]
We don't; we should fix all of these links at once like in the other PR.

Sorry for the late response here, I've been on vacation! Back now though.

**Pull request closed without merging**
