### PR TITLE
Fix several theme issues

### LINKED ISSUE #647: Page content overlaps search bar after search term is erased
If you search for something then erase the search term the content reappears and overlaps the search bar.

image

### PR DESCRIPTION
**Pull request by mattico**
Fixes #647

See the commit messages.

### CODE REVIEW

**Comment by Michael-F-Bryan** [comment]
Hmm, my concern here is it could be more of a band-aid solution than a real fix. I would have thought it'd be easy enough to use CSS to make sure the search bar doesn't overlap the content.

The root problem seems to be that we're using absolute positioning for the page content (so it'll leave space below the header bar) and that means other things can't flow/reposition themselves around it properly. If that's the case, the proper fix would probably be to remove the absolute positioning and `display: block` and position the page content differently... Would that work?

@sorin-davidoi, do you know of a way to make sure the search results+bar, page content, and top header bar can be positioned nicely using CSS?

**Comment by sorin-davidoi** [comment]
Don't think there is a nice way as long as absolute positioning is used.

**Comment by Michael-F-Bryan** [comment]
Do we need to use absolute positioning in the first place?

**Comment by mattico** [comment]
I agree re: bandaid solutions. This is what, the 3rd PR for a similar issue?

>I would have thought it'd be easy enough to use CSS to make sure the search bar doesn't overlap the content.

Possibly. My intent was just to fix the current behavior, but I suppose it'd be nice to show page content under the search.

**Comment by mattico** [comment]
Okay, you nerd-sniped me there :) There were a few small CSS issues that I've wanted to fix, so I fixed them. Before merging, I should go through the git-blame and make sure I'm not regressing anything by removing some CSS hacks. I'll leave that for later though since I've already spent too much time on this for today.

**Comment by mattico** [comment]
I think this is good to go. I tested it pretty thoroughly in FF, Chrome, Edge, and couldn't get anything to break.

**Comment by mattico** [comment]
Looks like rust 1.25 broke netbsd.... *sigh*

**Comment by mattico** [comment]
I'm going to see if a hello world fails to build on netbsd, report it upstream, then disable netbsd on travis.

**Comment by mattico** [comment]
There, rebased and working.

**Comment by Michael-F-Bryan** [comment]
And merged :tada:

**Comment by steveklabnik** [comment]
When is a release going to be made with this in it? It seems like this affects all of the books in the bookshelf 😅

**Comment by Michael-F-Bryan** [comment]
@steveklabnik I just pushed out a [new release]. Looking at the example book locally it seems like our previous styling problems are fixed :crossed_fingers: 

[new release]: https://crates.io/crates/mdbook/0.1.6

**Pull request merged**
