### PR TITLE
Exclude unnecessary items from package

### PR DESCRIPTION
**Pull request by lzutao**
r? @Dylan-DPC

### CODE REVIEW

**Comment by ehuss** [comment]
Is there a reason to change this?  It only saves about 3% of the package size.  It can be helpful to have these extra files (for example, crater can run tests against it).

**Comment by lzutao** [comment]
The only reason I thought is that dependencies of mdbook don't need those 
exluded files.

I don't know that crater depend on tests of package. I thought crater cloned
those package and tested crates. If this is right, I think rust team should state
that somewhere, and this PR will not need to be opened.

**Comment by lzutao** [comment]
Ping again. I talk a bit with infra team (pietro) and they think that
the crater stuff could be ignored.

**Comment by ehuss** [comment]
It's still not clear to me why this needs to change.  It only saves a few % of the package size.  What benefit does it have?

**Comment by Dylan-DPC** [comment]
@lzutao any updates on this

**Comment by lzutao** [comment]
I think I don't have strong opinions on this. Also @ehuss didn't want this. 
In this case, I would close this.

**Pull request closed without merging**
