### PR TITLE
can run tests of code block

### PR DESCRIPTION
**Pull request by mockersf**
for #451
added annotation "testable"
when annotation is present, a new button is added to run tests

### CODE REVIEW

**Comment by budziq** [comment]
Hi @mockersf sorry for taking so long. Thanks for the PR!

I'm not sure if we would like to add another button to the already crowded snippet button bar.
At the moment we are searching the snippet code for "feature" to switch to nightly compiler. How about we would do exactly the same, searching for "#[test]" making the switch to testing environment implicit? But I'm open to discussion.

**Comment by mockersf** [comment]
Hey @budziq 

I think it's interesting to be able to run the same code block as normal and as test, and have the output of each, so I decided to add a new button.
Otherwise, to show both, you would have to have the same code block twice, and they could get out of sync if they are user editable.

**Comment by budziq** [comment]
@mockersf do you have a usecase requiring to run both code (`fn main`) and tests in a single snippet that could not be achieved otherwise?

**Comment by mockersf** [comment]
For the example in https://rustbyexample.com/meta/test.html
For me the goal of this example was to show the different behaviour between `cargo run` and `cargo test`

**Comment by Michael-F-Bryan** [comment]
Other than that one Rust By Example case, I don't think there's ever going to be a time when you'll want to run a snippet as *both* a test or an executable, especially seeing as unless you do `#[cfg(not(test))] fn main() { ... }` you're going to get a compilation error. So to me it doesn't feel like adding a `testable` attribute and another button will pull its weight.

I'd be more inclined to updating the JS to act the same as the playground instead of adding another button to the already crowded button bar. So the PR could be reduced to something like this:

```diff
 function run_rust_code(code_block) {
      var result_block = code_block.find(".result");
      if(result_block.length === 0) {
          code_block.append("<code class=\"result hljs language-bash\"></code>");
         result_block = code_block.find(".result");
     }
 
     let text = playpen_text(code_block);
     
     var params = {
 	channel: "stable",
 	mode: "debug",
 	crateType: "bin",
+	tests: false,
 	code: text,
     }
 
     if(text.indexOf("#![feature") !== -1) {
          params.channel = "nightly";
      }
+
+    if(text.indexOf("#![test]") !== -1) {
+         params.test = true;
+     }
  
     result_block.text("Running...");

  ...  
}
```

**Comment by jhenninger** [comment]
I think this would be extremely helpful for the [The Book](https://doc.rust-lang.org/book/second-edition/index.html), especially the [Testing chapter](https://doc.rust-lang.org/book/second-edition/ch11-00-testing.html).

Right now mdbook [wraps code examples without a `fn main()` in its own main function block](https://github.com/rust-lang-nursery/mdBook/blob/master/src/renderer/html_handlebars/hbs_renderer.rs#L546-L561), which breaks the tests.

Some examples in The Book contain a "hidden" and empty main function before the test module, but not all do. 

Best approach would probably be to not wrap the example if the code block has the "testable" CSS class and remove the empty main functions from the book.

**Comment by simonhdickson** [comment]
I was just about to create a PR for this when I spotted one was open. Is this PR still active?

**Comment by Dylan-DPC** [comment]
I'm closing this PR based on the feedback received and inactivity. Thanks for contributing.

**Pull request closed without merging**
