### PR TITLE
Remove rustfmt.toml

### PR DESCRIPTION
**Pull request by mattico**
Removes `rustfmt.toml` as discussed in #688.

### CODE REVIEW

**Comment by azerupi** [comment]
Thanks!
Did you run rustfmt without config on the code base?
I there are any changes, it might be worth including them in this PR to avoid noise in the next PR that runs rustmft.

**Comment by mattico** [comment]
I didn't do that in this PR because it would cause rebase churn for other branches/PRs. I suppose we have to do it at some point, though, might as well do it all at once.

**Comment by Michael-F-Bryan** [comment]
I'd be happy with removing `rustfmt.toml` and just falling back to the defaults. They're pretty good now.

@mattico, is this ready to merge?

**Comment by mattico** [comment]
I feel like there should be a merge conflict by now, but GitHub seems to think not. That's my only concern with merging.

**Pull request merged**
