### PR TITLE
Fix issue #703.

### PR DESCRIPTION
**Pull request by basbossink**
Implemented the proposed change in wording.

### CODE REVIEW

**Comment by ehuss** [comment]
I think it will need to cover the page title, all the links to the page, etc.  I would search through the whole project to make sure everything is updated.

**Comment by basbossink** [comment]
Great minds think alike ;-) that is exactly what I have done, there was only one change using search and replace on the entire documentation.

**Comment by Dylan-DPC** [comment]
Thanks

**Comment by ehuss** [comment]
I don't understand.  This patch only updates one location.  The phrase "alternate backend" appears in several other locations, particularly as the title of that page, several other places on that page, SUMMARY.md, for_developers/README.md, and various places in the code.

**Comment by Dylan-DPC** [comment]
Oops yeah didn't check that. There are 3 more [instances](https://github.com/rust-lang-nursery/mdBook/search?q=alternate+backend&unscoped_q=alternate+backend)

**Comment by basbossink** [comment]
I don't know what went wrong with the search and replace earlier, anyway all occurrences should be updated. The test file named `alternate_backends.rs` has also been renamed.

**Comment by Dylan-DPC** [comment]
@basbossink where it has been updated?

**Comment by basbossink** [comment]
See PR #929. Sorry for the confusion I thought updates to the branch in my fork would show up here automagically.

**Pull request merged**
