### PR TITLE
Make serve and watch respect .gitignore

### PR DESCRIPTION
**Pull request by fmanco**
When editing files with some editors (e.g. vim) temporary files are
constantly being modified causing mdbook serve and watch to constantly
rebuild the project.

To avoid this leverage the ignore crate to load the project's root
.gitignore file and skip changes on files ignored.

### CODE REVIEW

**Comment by ehuss** [comment]
Sorry, I'm a bit confused. Was it just coincidence that this and #1044 were opened within a few hours of each other?

**Comment by segfaultsourcery** [comment]
@ehuss It's likely a hilarious coincidence. I did open a thread on /r/rust asking for input (I'll be making good use of that advice in a bit), so maybe @fmanco wanted to provide me with a better example? :)

**Comment by fmanco** [comment]
What's better than 1 PR... 2 PRs. Kidding, this was a coincidence. @segfaultsourcery this is my first code in Rust which I'm learning just now, better examples is likely not something you'll get from me any time soon 😄 .

I'm fine with dropping this and just going with #1044 if you prefer. Only did this for learning and because the constant refreshing was annoying me. As long as we get something I'm happy.

**Comment by segfaultsourcery** [comment]
I've only been writing it for a couple of months, myself. I'm also happy either way, I just want the itch scratched.

**Comment by fmanco** [comment]
Let's go with yours @segfaultsourcery I'm not going to be able to put much time into this and you already got some feedback from r/rust which is great. Thanks for working on it.

**Comment by segfaultsourcery** [comment]
Oh I was just going to wait for input from the others on how to proceed.
Anyway, you have one very neat thing that I didn't think of, and that's
adding the command line param for enabling gitignore. In my case, it's just
always enabled. If you want, you can make a pull request to me so we both
get our names on this. I can also loop you in if I get any requests.

**Comment by fmanco** [comment]
@segfaultsourcery I had no time to follow up on this, I'm glad your PR got merged. Once I have a bit of time I will make a new PR for the command line flag.

**Comment by segfaultsourcery** [comment]
Hey! No worries.

It turns out that they didn't want a flag (check the discussion in the
pull), so instead were searching backwards for a .gitignore through the
ancestors of the current folder.

I don't think it's released yet, but it does work if you `cargo install
--git` the master branch.
Just add a line with "*.swp" (I think it was for you?) and it should work.

**Comment by fmanco** [comment]
Awesome. Thanks for the work. This is great.

**Pull request closed without merging**
