### PR TITLE
add an example for custom css and js

### PR DESCRIPTION
**Pull request by dns2utf8**
It took me a bit to get it working.

I added the examples for people like me, who do look at the example, the docs and the code in that order.

Best regards

### CODE REVIEW

**Comment by Michael-F-Bryan** [comment]
When I did the config PR I updated `config.md`, so things may have moved around a bit. Hopefully it's easy enough to figure out how to resolve the merge conflict. Sorry @dns2utf8!

**Comment by Michael-F-Bryan** [comment]
@dns2utf8, would you be able to resolve the conflicts so we can merge this PR?

**Comment by Michael-F-Bryan** [comment]
Thanks for looking at this again @azerupi, I agree that I think it's probably best to close the PR. @dns2utf8 let us know if you want us to re-open it.

**Comment by wycats** [comment]
fwiw, I was looking for the answer to this question and found it in this closed comment. That suggests that maybe the commit should have been merged?

**Comment by wycats** [comment]
@azerupi ping

**Pull request closed without merging**
