### PR TITLE
Include Cargo.lock

### PR DESCRIPTION
**Pull request by Havvy**
The guidelines say that applications should check in the Cargo.lock file, and I need a Cargo.lock file to be in-repo for including mdbook into nixpkgs.

### CODE REVIEW

**Comment by Michael-F-Bryan** [comment]
I've actually wondered the same thing. Thanks for the PR!

**Comment by Havvy** [comment]
Per chance, can you release a 0.1.3 with the Cargo.lock? Or are you waiting for some other features/bugfixes to land?

**Comment by Michael-F-Bryan** [comment]
I don't believe we're waiting on anything. I'll make a new release when I get home from work.

**Comment by Michael-F-Bryan** [comment]
@Havvy, Done!

**Pull request merged**
