### PR TITLE
Fix broken cache by updating sccache version

### LINKED ISSUE #957: sccache broken in CI
I've noticed that caching seems to be broken on CI.  The `custom_preprocessors` test runs `cargo run --example nop-preprocessor` several times for different tests.  Each time it runs, it rebuilds mdbook from scratch, which takes a very long time.

I cleared the caches on Travis, which seemed to fix it temporarily, but it is breaking again.  Here is an example: https://travis-ci.com/rust-lang-nursery/mdBook/jobs/209111625

@lzutao Can you fix this, or remove the use of sccache?  I personally don't feel like the extra complications from sccache or worth it, but perhaps there is a simple fix.

### PR DESCRIPTION
**Pull request by lzutao**
Fixes #957 
cc @ehuss

### CODE REVIEW

**Comment by lzutao** [comment]
The build is failing. I believe clearing the CI cache and restart build job will help.

**Comment by lzutao** [comment]
The build now passed on Travis with 2ebf22d: https://travis-ci.com/rust-lang-nursery/mdBook/builds/116462923

**Comment by lzutao** [comment]
Ping @ehuss

**Comment by ehuss** [comment]
Do you know why all the Travis jobs are now failing?

**Comment by lzutao** [comment]
It was my mistake because of `sh -ex` line in rustfmt parts.

**Comment by lzutao** [comment]
It is good now.

**Comment by ehuss** [comment]
Thanks!

**Pull request merged**
