### PR TITLE
Put the search bar into an HTML form

### PR DESCRIPTION
**Pull request by mbrubeck**
This enables "Add a keyword for this search" in the contex menu for the
search field, in Firefox and other browsers.

### CODE REVIEW

**Comment by mattico** [comment]
This also causes the browser to show the form submission history pop-up, which seems good, and causes the browser to submit/reload when you hit enter, which seems fine. LGTM

**Comment by mbrubeck** [comment]
It probably makes sense to prevent the form submission behavior, since it causes an unnecessary reload.

**Comment by mbrubeck** [comment]
> It probably makes sense to prevent the form submission behavior, since it causes an unnecessary reload.

Done.  Note, this is also what rustdoc does for its search form.

**Comment by Michael-F-Bryan** [comment]
I just tried this out locally, looks good to me :+1:

**Pull request merged**
