### PR TITLE
Update to pulldown-cmark 0.5.

### PR DESCRIPTION
**Pull request by ehuss**
- Update to 0.5.2.
- Remove pulldown-cmark-to-cmark and de-emphasis test, incompatible with 0.5.

### CODE REVIEW

**Comment by ehuss** [comment]
This includes a temporary hack to deal with pulldown-cmark-to-cmark needing to be updated (see https://github.com/Byron/pulldown-cmark-to-cmark/pull/2). Can either wait for that PR to be merged, or remove the example altogether, or leave the hack.

This causes some changes in rendering in various rust-lang books since pulldown-cmark better conforms to the markdown spec. If this is merged, there will need to be some coordination in updating the books to fix some bugs. I can handle that, just a heads up. Not sure if this warrants bumping to 0.3 (I don't think so).

**Comment by Dylan-DPC** [comment]
Thanks. i'd prefer to wait for that PR to be merged.

**Comment by ehuss** [comment]
I have updated this to 0.5 and removed the pulldown-cmark-to-cmark dependency.  I think the no-op example is sufficient to demonstrate how to make a preprocessor. The de-emphasis one didn't work by itself, anyways.  I did make a demo using comrak instead (https://github.com/ehuss/mdBook/commit/98dbc8f318695ea21b7128ccb66f53473ffbd3bb if you're curious), which works better than the original. But I think the additional dependencies are too heavy, and it seems to be getting a little convoluted for a simple demonstration.

**Comment by Dylan-DPC** [comment]
@ehuss can you resolve the conflicts on this?

**Comment by lzutao** [comment]
@ehuss You have conflict to solve.

**Comment by ehuss** [comment]
Updated!

**Comment by lzutao** [comment]
I think you need a rebase and update pulldown-cmark to 0.5.2 .
r=me with nits fixed.

**Comment by ehuss** [comment]
Thanks @lzutao. I wish github would notify automatically like bors does.

**Pull request merged**
